=== geschwaerzler/java-xml-tool/src/main/resources/addressbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://xmllab.fhv.at/addressbook"
	targetNamespace="http://xmllab.fhv.at/addressbook"
	elementFormDefault="qualified">
	
	<xsd:element name="addressbook" type="addressbook-type"/>
	<xsd:element name="address" type="address-type"/>
	<xsd:element name="person" type="person-type"/>
	<xsd:element name="firstname" type="xsd:string"/>
	<xsd:element name="lastname" type="xsd:string"/>
	<xsd:element name="street" type="xsd:string"/>
	<xsd:element name="zip" type="xsd:string"/>
	<xsd:element name="city" type="xsd:string"/>
	<xsd:element name="country" type="xsd:string"/>
	
	<xsd:complexType name="addressbook-type">
	   <xsd:sequence>
           <xsd:element ref="person" maxOccurs="unbounded"/>
	   </xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="address-type">
	   <xsd:sequence>
	       <xsd:element ref="street"/>
	       <xsd:element ref="zip"/>
	       <xsd:element ref="city"/>
	       <xsd:element ref="country" minOccurs="0"/>
	   </xsd:sequence>
	   <xsd:attribute name="type" type="address-type-enum" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="person-type">
	   <xsd:sequence>
	       <xsd:element ref="firstname"/>
	       <xsd:element ref="lastname"/>
	       <xsd:element ref="address" maxOccurs="unbounded"/>
	   </xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="address-type-enum">
	   <xsd:restriction base="xsd:string">
	       <xsd:enumeration value="work"/>
	       <xsd:enumeration value="home"/>
	   </xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== geschwaerzler/java-xml-tool/xml/addresses.xml
<?xml version="1.0" encoding="UTF-8"?>

<addressbook
	xmlns="http://xmllab.fhv.at/addressbook"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmllab.fhv.at/addressbook addressbook.xsd "
>
    <person>
        <firstname>Gerhard</firstname>
        <lastname>Schwärzler</lastname>
        <address type="home">
            <street>Rathausstraße 2</street>
            <zip>6900</zip>
            <city>Bregenz</city>
        </address>
        <address type="work">
            <street>Achstraße 1</street>
            <zip>6850</zip>
            <city>Dornbirn</city>
        </address>
    </person>
    
    <person>
        <firstname>Regine</firstname>
        <lastname>Bolter</lastname>
        <address type="work">
            <street>Achstraße 1</street>
            <zip>6850</zip>
            <city>Dornbirn</city>
            <country>Austria</country>
        </address>
    </person>
    
</addressbook>
